spring.datasource.url=jdbc:postgresql://dpg-d720hcvfte5s73ag54t0-a/online_voting_system_5o4u
spring.datasource.username=online_voting_system_5o4u_user
spring.datasource.password=xMGzC4ByXhLjvMdNhnZpSRFz1USrlGEk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
